apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-nginx-deployment
  labels:
    app: app3-nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: app3-nginx
  template:
    metadata:
      labels:
        app: app3-nginx
    spec:
      containers:
        - name: app3-nginx
          image: 210613553230.dkr.ecr.us-east-1.amazonaws.com/eks-demo:19
          ports:
            - containerPort: 80
